# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  # Ferdig orb som blant annet inkluderer Docker Hub-pålogging ferdig satt opp for navikt
  nais: 'navikt/nais-deployment@3.2.1'

jobs:
  build:
    docker:
      # Av en eller annen grunn fungerer det ikke å bare bruke siste JDK 8 (circleci/openjdk:8)
      - image: circleci/openjdk:8u171-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/melosys-kodeverk-java

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Bygger prosjektet, og generer kjørbar jar
      - run:
          command: |
            mvn install -B -V
      # Ber om at orb-en skal bygge fra ./Dockerfile og deploye til Docker Hub
      - nais/docker:
          image: navikt/melosys-kodeverk-java

workflows:
  build-and-deploy:
    jobs:
      - build:
          # Må settes for å aktivere orb-funksjonaliteten
          context: NAIS deployment
