spring:
  main:
    web-application-type: NONE
generator:
  generert:
    modul-mappe: melosys-internt-kodeverk
    kildekode-mappe: ${generator.generert.modul-mappe}/src/main/java
    kodeverk-mappe: ${generator.generert.kildekode-mappe}/no/nav/melosys/domain/kodeverk
  ressurser:
    template-mappe: /templates
    standard-enum-filer: 
      - Kodeverk
      - LovvalgBestemmelse
    kodeverk-template: Kodeverk.ftlh
#  versjon-fil: melosys-kodeverk-generator/src/test/resources/dist/semver.txt
#  kodeverk-Yaml: melosys-kodeverk-generator/src/test/resources/dist/kodemap.yml
  lovvalgBestemmelse-enum-filer: 
    - Forordning_883_2004
    - Forordning_987_2009
    - Tillegg
  pakke-navn: no.nav.melosys.domain.kodeverk
   
